import type { MetadataRoute } from 'next';

/**
 * Web app manifest — required before iOS will treat the home-screen install as
 * a real web app (standalone shell, and the prerequisite for Web Push on
 * iOS 16.4+). Icons are generated by scripts/generate-icons.mjs from the logo
 * mark in components/Logo.tsx.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: '4WARD — One crew. One direction.',
    short_name: '4WARD',
    description:
      "The crew's shared development tracker — 70 stats, 7 categories, one direction: forward.",
    start_url: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
    background_color: '#0a0a0f',
    theme_color: '#0a0a0f',
    categories: ['lifestyle', 'productivity'],
    icons: [
      { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      // Maskable variants keep the mark inside the safe zone when Android
      // crops the icon to a circle/squircle.
      { src: '/icon-maskable-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
      { src: '/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
    shortcuts: [
      { name: 'Evidence board', short_name: 'Evidence', url: '/evidence' },
      { name: 'Suggestions', short_name: 'Suggest', url: '/suggestions' },
      { name: 'Message board', short_name: 'Board', url: '/messages' },
    ],
  };
}
