export const STAT_DESCRIPTIONS: Record<string, string> = {
  'mtl-a': 'Maintains high self-belief even after failures or criticism.',
  'mtl-b': 'Consistently rises and performs better under stress or tight deadlines.',
  'mtl-c': 'Regularly thinks outside the box and generates innovative solutions.',
  'mtl-d': 'Never settles; always pushes for the absolute best version of what they can achieve.',
  'mtl-e': 'Views challenges and setbacks as opportunities to improve rather than threats.',
  'mtl-f': 'Quickly bounces back from disappointment, rejection, or bad days.',
  'mtl-g': 'Maintains sharp concentration and avoids mental fog for long periods.',
  'mtl-h': 'Uses constructive internal dialogue instead of harsh self-criticism.',
  'mtl-i': 'Daily actions consistently match big-picture life goals and values.',
  'mtl-j': 'Thrives in ambiguous or rapidly changing situations without panicking.',

  'phy-a': 'General strength. How strong is this person?',
  'phy-b': 'Excellent stamina for sustained effort (e.g., long runs, high-intensity intervals).',
  'phy-c': 'Fast hands and quick reflexes (measurable via apps or drills).',
  'phy-d': 'Top-tier acceleration and short-distance speed.',
  'phy-e': 'Impressive explosive power (track jump height).',
  'phy-f': 'Superior stability and body control. General balance.',
  'phy-g': 'Lean, muscular, well-proportioned physique with low body fat.',
  'phy-h': 'High impact power in punches or strikes (if relevant to your training).',
  'phy-i': 'Strong pushing strength (Is able to generate large amounts of pushing force)',
  'phy-j': 'Precise accuracy and timing in sports, gaming, or skill-based activities.',

  'kno-a': 'Strong grasp of finance, marketing, management, and strategy.',
  'kno-b': 'Deep understanding of rules, tactics, history, and current events in multiple sports.',
  'kno-c': 'Broad awareness of history, geography, science, and culture.',
  'kno-d': 'Up-to-date on trends in music, movies, TV, memes, and entertainment.',
  'kno-e': 'Well-informed on politics, global events, and economics without bias overload.',
  'kno-f': 'High-level understanding in chosen fields (math, literature, tech, etc.).',
  'kno-g': 'Insight into how people think, motivate, and act.',
  'kno-h': 'Advanced knowledge of investing, budgeting, taxes, and wealth-building.',
  'kno-i': 'Evidence-based understanding of fitness, diet, and wellness.',
  'kno-j': 'Familiar with emerging tech, AI, tools, and societal shifts.',

  'strs-a': 'Quickly understands others\' intentions and adjusts behavior accordingly.',
  'strs-b': 'Picks up practical skills and lessons rapidly from real experiences.',
  'strs-c': 'Notices and capitalizes on chances others miss in everyday life.',
  'strs-d': 'Skillfully dodges scams, bad deals, or manipulative people (especially in relationships).',
  'strs-e': 'Finds creative solutions using available resources without formal guidance.',
  'strs-f': 'Navigates deals, conflicts, or conversations to favorable outcomes.',
  'strs-g': 'Constantly reads environments and potential dangers/opportunities.',
  'strs-h': 'Doesn\'t overly depend on institutions or "the system" for basic success. (needs to be taught something to learn, doesn\'t come up with it on his own)',
  'strs-i': 'Understands "how the world really works" (networks, unspoken rules) without engaging in risky street life.',
  'strs-j': 'Protects time, energy, and reputation from toxic influences or setups.',

  'stra-a': 'Sets clear, multi-year goals and breaks them into actionable steps.',
  'stra-b': 'Consistently delays gratification for bigger future payoffs.',
  'stra-c': 'Quickly adjusts strategies when the situation or "rules" change.',
  'stra-d': 'Anticipates and creates/dodges strategic advantages/pitfalls.',
  'stra-e': 'Stays calm and clear-headed when planning high-stakes or chaotic scenarios.',
  'stra-f': 'Thinks several moves ahead and prepares for multiple possible outcomes.',
  'stra-g': 'Optimally assigns time, money, and energy across competing priorities.',
  'stra-h': 'Makes smart, fast decisions when plans suddenly shift.',
  'stra-i': 'Accurately weighs probabilities and consequences before acting.',
  'stra-j': 'Always has backup plans and "Plan B/C" options ready.',

  'ski-a': 'World-class or near-elite proficiency in 1–3 key skills that matter most.',
  'ski-b': 'Competent across a wide range beyond their main zone of comfort.',
  'ski-c': 'Picks up new complex skills quickly through focused effort.',
  'ski-d': 'Actively learns and practices new skills without external pressure.',
  'ski-e': 'Applies abilities from one area effectively to others.',
  'ski-f': 'Regularly trains skills with focused, high-quality methods.',
  'ski-g': 'Can clearly teach or demonstrate skills to others.',
  'ski-h': 'Modifies or combines skills to fit new contexts or challenges.',
  'ski-i': 'Has tangible proof (projects, performances, results) of abilities.',
  'ski-j': 'Regularly audits and upgrades the skillset to stay relevant and competitive.',

  'enr-a': 'Looks energetic, healthy, vibrant, and well-groomed (bright eyes, clear skin, strong posture).',
  'enr-b': 'Commands attention positively when entering a space; people naturally notice and remember them.',
  'enr-c': 'Speaks with enthusiasm, warmth, confidence, and varied tone instead of being flat or hesitant.',
  'enr-d': 'Expresses ideas clearly, concisely, and persuasively without filler or confusion.',
  'enr-e': 'Uses open, confident, engaging gestures, maintains strong eye contact, and projects power.',
  'enr-f': 'Naturally lifts the mood of groups; people feel more positive, motivated, or energized after interacting.',
  'enr-g': 'Maintains high energy during long interactions or events without becoming drained or negative.',
  'enr-h': 'People instinctively listen, respect, and defer to them in group settings.',
  'enr-i': 'Motivates and brings out the best in others, making people want to take action or follow.',
  'enr-j': 'Stays composed, makes clear decisions, and guides others effectively through pressure or chaos.',
};
